# Generated by Django 5.0.6 on 2024-07-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calimaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifer_cal', models.CharField(default='Unknown', max_length=20)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(default='Pending', max_length=20)),
                ('fecha_de_modificacion', models.DateTimeField()),
                ('usuario', models.CharField(default='Unknown', max_length=20)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('cantidad', models.IntegerField(default=0)),
                ('id_externo', models.CharField(default='Unknown', max_length=20)),
                ('metodo', models.TextField(default='N/A')),
                ('respuesta', models.TextField(default='N/A')),
                ('agente', models.IntegerField(default=0)),
                ('fecha_de_registro_del_jugador', models.DateTimeField()),
            ],
            options={
                'db_table': 'CALIMACO',
            },
        ),
        migrations.CreateModel(
            name='GestionRW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField()),
                ('local', models.CharField(max_length=100)),
                ('registro', models.DateTimeField()),
                ('tipo', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('bono', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20)),
                ('web_id', models.IntegerField()),
                ('cliente', models.CharField(max_length=255)),
                ('recarga', models.IntegerField()),
                ('bono_5_por_ciento', models.IntegerField()),
                ('promotor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'GESTION_RW',
            },
        ),
        migrations.CreateModel(
            name='Skype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('monto', models.CharField(max_length=20)),
                ('tx', models.BigIntegerField(default=0)),
                ('id_web', models.BigIntegerField()),
                ('promotor', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=255)),
                ('teleservicios', models.CharField(max_length=50)),
                ('soporte', models.CharField(max_length=50)),
                ('calimaco', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SKYPE',
            },
        ),
        migrations.CreateModel(
            name='TicketsPagadosDeTienda',
            fields=[
                ('ticket', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField()),
                ('zona_creadora', models.CharField(max_length=100)),
                ('caja_creadora', models.CharField(max_length=100)),
                ('usuario_creador', models.CharField(max_length=100)),
                ('razon_social_creador', models.CharField(max_length=255)),
                ('fecha_calculo', models.DateTimeField()),
                ('fecha_pago', models.DateTimeField()),
                ('caja_pagadora', models.CharField(max_length=100)),
                ('usuario_pagador', models.CharField(max_length=100)),
                ('razon_social_pagador', models.CharField(max_length=255)),
                ('monto_apostado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_doc_cliente', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TICKETS_PAGADOS_DE_TIENDA',
            },
        ),
    ]
